//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issues
    {
        public int IssueId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
    }
}
